### ISSUE TITLE
Gradle dependency support

### ISSUE THREAD

**Issue by erf** [tsums/AndroidCookieJar#2]
I would like to add your library as an gradle dependecy, any plans on supporting this?

**Comment by tsums** [comment]
It's definitely something I would like to do. I need to find time to go back and polish this a bit, and learn how to get things onto maven central/jcenter. With your interest I'll probably get to that soon.

**Comment by tsums** [comment]
I just published the project to Bintray and sent in a request to have it included in jcenter. In the meantime, you can add the following to your project build.gradle and then follow the readme to use it as a gradle dependency.

```
repositories {
    maven {
        url  "http://dl.bintray.com/tsums/maven" 
    }
}
```

**Comment by erf** [comment]
Hey! Thanks, great work! :)
