### ISSUE TITLE
Include base64 library in project

### ISSUE THREAD

**Issue by erf** [tsums/AndroidCookieJar#3]
Would be easier for user (me;) if the base64 library was included.

**Comment by tsums** [comment]
Once I get this running as a gradle dependency it should be able to fetch that dependency during your gradle sync, which should make it transparent.

**Comment by tsums** [comment]
I have simplified this so you simply include base64coder in your dependencies along with the library.

**Comment by ofields** [comment]
The base64coder dependency shouldn't be necessary. Android ships with base64 utility methods as of API level 8: http://developer.android.com/reference/android/util/Base64.html
